### ISSUE TITLE
yetanalytics/persephone:latest - repository does not exist

### ISSUE THREAD

**Issue by ivoloshin** [yetanalytics/project-persephone#47]
Could you please publish yetanalytics/persephone to docker hub?

Thank you

**Comment by kelvinqian00** [comment]
Persephone should be available on DockerHub already: https://hub.docker.com/repository/docker/yetanalytics/persephone

**Comment by ivoloshin** [comment]
Thank you for the quick reply. I still cannot access it - is it set private by any chance?

**Comment by kelvinqian00** [comment]
That indeed seems to be the problem. I just set it to public.

**Comment by ivoloshin** [comment]
Thank you very much!
